## 데이터 저장법

1. 이미지를 숫자로 나타내기(EX. A=1, B=2...)


In [1]:
x_data = [[0,1,2,3,4]]

2. one-hot encoding(내가 표현하고자 하는 값을 벡터로 표현함)

In [2]:
## hell0를 표현하고자 할 때
x_hot = [[1,0,0,0,0],
         [0,1,0,0,0],
         [1,0,0,0,0],
         [0,0,1,0,0],
         [0,0,0,1,0],
         [0,0,0,1,0]]

y_data = [[1,0,2,3,3,4]]

##  Cross Entropy Loss

다음 단어를 예측하는 알고리즘의 경우, input 값에 따라 결과 값에서 무엇이 올 확률이 가장 높은지 계산해야 함

따라서 cross etropy loss를 사용해 결과값을 예측

## 1. one hot 인코딩

In [3]:
import torch

char = ['h','i','e','l','o']
input_size = len(char)
hideen_size = len(char) ##값 달라도 상관 x
learning_rate=0.1

x_data = [[0,1,0,2,3,3]]
##o를 예측하는 코드이므로 0을 뺐다.
x_hot = [[1,0,0,0,0],
         [0,1,0,0,0],
         [1,0,0,0,0],
         [0,0,1,0,0],
         [0,0,0,1,0],
         [0,0,0,1,0]]

y_data = [[1,0,2,3,3,4]]

x=torch.FloatTensor(x_hot)
y=torch.FloatTensor(y_data)

print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.]])


## 문자열 시퀀스

In [4]:
import numpy as np

word = "hihello"

char = list(set(word))
print("char detail:",char,'\n')
##set은 순서를 보존하지 않는다. 순서가 이상할 수 있음

char detail: ['i', 'o', 'e', 'h', 'l'] 



In [5]:
char_dic = {c:i for i,c in enumerate(char)}
print("dictionary detail:",char_dic,'\n')
## char에 있는 문자에 대해 i로 순서를 매핑한다.

dictionary detail: {'i': 0, 'o': 1, 'e': 2, 'h': 3, 'l': 4} 



In [6]:
dic_size = len(char_dic)
hidden_size = len(char_dic)
##hideen_size는 변경 가능하다.
learning_rate = 0.1

In [7]:
word_idx = [char_dic[c] for c in word]
print("maked array:",word_idx,'\n')
##word에 있는 글자에 따라 char_dic[c] value값을 나열한다.(ex. 3,1,2..)

maked array: [3, 0, 3, 2, 4, 4, 1] 



In [8]:
x_data = [word_idx[:-1]]
##맨 마지막 값만 빼고 전부 하나의 리스트로

x_one_hot = [np.eye(dic_size)[x] for x in x_data]
'''
one-hot 인코딩을 하는 코드다.
np.eye(dic_size) : dic_size 만큼크기의 매트릭스 생성
dic_size = 5이다. 즉슨 5x5 배열 생성
기본은 대각선이 1이고, 나머지가 0인 배열이 생성되나 [x]로 1 위치 지정 가능

x_data에 해당하는 x 위치에 1을 놓고, 나머지는 0으로 채운다.
위 방식을 통해 one-hot encoding을 할 수 있다.
'''

print(x_one_hot)


[array([[0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]])]


In [9]:
y_data = [word_idx[1:]]
print("y data:",y_data)

y data: [[0, 3, 2, 4, 4, 1]]


In [10]:
x = torch.FloatTensor(x_one_hot)
y= torch.LongTensor(y_data)

print(x)
print(y)

tensor([[[0., 0., 0., 1., 0.],
         [1., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 1.]]])
tensor([[0, 3, 2, 4, 4, 1]])


C:\Users\kuroc\AppData\Local\Temp\ipykernel_9832\2614910100.py:1: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at C:\cb\pytorch_1000000000000\work\torch\csrc\utils\tensor_new.cpp:264.)
  x = torch.FloatTensor(x_one_hot)


## 실제 RNN 학습

In [11]:
import torch.optim as optim

print(input_size, hidden_size)
RNN = torch.nn.RNN(input_size, hidden_size, batch_first=True)
'''
input size, hiddeb_size: hihell 길이
o를 예측하는 것이므로 o까지 포함 x
batch_size를 자동으로 입력하기 위해, batch_first를 True로 설정
'''

5 5


'\ninput size, hiddeb_size: hihell 길이\no를 예측하는 것이므로 o까지 포함 x\nbatch_size를 자동으로 입력하기 위해, batch_first를 True로 설정\n'

In [12]:
criterion = torch.nn.CrossEntropyLoss()
optimizer = optim.Adam(RNN.parameters(), lr=learning_rate)

In [13]:
for i in range(100):
    
    ##outputs: 실제로 나오는 H의 값(5x5 텐서로 입력되었으므로 5x5 크기이다)
    ##_status는 다시 순환해서 학습하는 값
    optimizer.zero_grad()
    outputs, _status = RNN(x)
    
    ##손실 계산
    loss = criterion(outputs.view(-1, input_size), y.view(-1))
    
    loss.backward()
    optimizer.step()

    ##3차원 입력값 중에서, 가장 큰 값을 찾는다.(axis=2 = 3차원)
    result = outputs.data.numpy().argmax(axis=2)

    #result는 squeeze를 통해 1차원 배열로 바뀐다.
    #join [c]를 통해 char[c]에 해다하는 글자를 하나로 합친 단어로 만든다.
    result_s = ''.join([char[c] for c in np.squeeze(result)])
    if i%10 ==0:
        print("[epoch", i, "]:", loss.item(), "prediction:", result, "true Y:", y_data, "prediction str:", result_s)

[epoch 0 ]: 1.778258204460144 prediction: [[3 0 3 0 3 3]] true Y: [[0, 3, 2, 4, 4, 1]] prediction str: hihihh
[epoch 10 ]: 0.8783188462257385 prediction: [[0 3 2 4 4 4]] true Y: [[0, 3, 2, 4, 4, 1]] prediction str: ihelll
[epoch 20 ]: 0.6632985472679138 prediction: [[0 3 2 4 4 4]] true Y: [[0, 3, 2, 4, 4, 1]] prediction str: ihelll
[epoch 30 ]: 0.5877516865730286 prediction: [[0 3 2 4 4 4]] true Y: [[0, 3, 2, 4, 4, 1]] prediction str: ihelll
[epoch 40 ]: 0.5203302502632141 prediction: [[0 3 2 4 4 1]] true Y: [[0, 3, 2, 4, 4, 1]] prediction str: ihello
[epoch 50 ]: 0.4874875247478485 prediction: [[0 3 2 4 4 1]] true Y: [[0, 3, 2, 4, 4, 1]] prediction str: ihello
[epoch 60 ]: 0.47347167134284973 prediction: [[0 3 2 4 4 1]] true Y: [[0, 3, 2, 4, 4, 1]] prediction str: ihello
[epoch 70 ]: 0.46745744347572327 prediction: [[0 3 2 4 4 1]] true Y: [[0, 3, 2, 4, 4, 1]] prediction str: ihello
[epoch 80 ]: 0.46401306986808777 prediction: [[0 3 2 4 4 1]] true Y: [[0, 3, 2, 4, 4, 1]] prediction str

In [21]:
import numpy as np
import torch
from torch import optim

sentence = "I am so happy to study RNN. There are so many things to study. It's amazing."

x_data = []
y_data = []
sequence_length = 15
hidden_size = input_size = sequence_length

char_dic = {char: i for i, char in enumerate(set(sentence))}
dic_size = len(char_dic)

for i in range(0, len(sentence) - sequence_length):
    x_str = sentence[i:i + sequence_length]
    y_str = sentence[i + 1:i + sequence_length + 1]

    print(i, x_str, '->', y_str)
    x_data.append([char_dic[c] for c in x_str])
    y_data.append([char_dic[c] for c in y_str])

x_one_hot = [np.eye(dic_size)[x] for x in x_data]

x = torch.FloatTensor(x_one_hot)
y = torch.LongTensor(y_data)

class Net(torch.nn.Module):
    def __init__(self, input_dim, hidden_dim, layers):
        super(Net, self).__init__()
        self.rnn = torch.nn.RNN(input_dim, hidden_dim, num_layers=layers, batch_first=True)
        self.fc = torch.nn.Linear(hidden_dim, dic_size, bias=True)

    def forward(self, x):
        x, _status = self.rnn(x)
        x = x[:, -1, :]  # RNN 레이어의 출력 중 마지막 타임 스텝만 사용
        x = self.fc(x)
        return x

net = Net(dic_size, hidden_size, 2)

criterion = torch.nn.CrossEntropyLoss()
optimizer = optim.Adam(net.parameters(), lr=0.01)
for i in range(100):
    optimizer.zero_grad()
    outputs = net(x)

    # outputs에 softmax를 적용하지 않고 손실을 계산
    loss = criterion(outputs.view(-1), y.view(-1))
    
    loss.backward()
    optimizer.step()

    result = outputs.argmax(dim=1)

    predict_str = "".join([char for char in sentence[i:i+sequence_length]]) + ''.join([char for char in result])
    print(i, predict_str, loss.item())


0 I am so happy t ->  am so happy to
1  am so happy to -> am so happy to 
2 am so happy to  -> m so happy to s
3 m so happy to s ->  so happy to st
4  so happy to st -> so happy to stu
5 so happy to stu -> o happy to stud
6 o happy to stud ->  happy to study
7  happy to study -> happy to study 
8 happy to study  -> appy to study R
9 appy to study R -> ppy to study RN
10 ppy to study RN -> py to study RNN
11 py to study RNN -> y to study RNN.
12 y to study RNN. ->  to study RNN. 
13  to study RNN.  -> to study RNN. T
14 to study RNN. T -> o study RNN. Th
15 o study RNN. Th ->  study RNN. The
16  study RNN. The -> study RNN. Ther
17 study RNN. Ther -> tudy RNN. There
18 tudy RNN. There -> udy RNN. There 
19 udy RNN. There  -> dy RNN. There a
20 dy RNN. There a -> y RNN. There ar
21 y RNN. There ar ->  RNN. There are
22  RNN. There are -> RNN. There are 
23 RNN. There are  -> NN. There are s
24 NN. There are s -> N. There are so
25 N. There are so -> . There are so 
26 . There are so  -> 

RuntimeError: size mismatch (got input: [1403], target: [915])