In [27]:

##logistic Regression
##: m x d 크기의 데이터에서  m개의 결과 도출(결과값: 이진값)

##시그모이드 함수 통해서 결과값 자연스럽게 해줌
''' 시그모이드 함수 H(x) = 1/(1+e^(-(w^T)*w)임
    가중치 e^(-(w^T)*w)는 각 데이터의 가중치(w)와 각각의 데이터를 곱한 값을 더한 값을 의미함
    '''

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

torch.manual_seed(1) ## 항상 동일한 랜덤값이 나오도록 시드 설정(다시 코드 실행해도 동일 시드 출현=재현성 UP


In [55]:
x_data = [[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]] ##6 x 2데이터

##6x2의 입력값을 받았으므로 6개의 결과값 존재해야 함
##각각의 값은 이진값(시그모이드 함수 사용할 예정)
y_data = [[0],[0],[0],[1],[1],[1]]


In [56]:

x_train=torch.FloatTensor(x_data)
y_train=torch.FloatTensor(y_data)

##각각의 데이터를 전부 FloatTensor화 해줌


In [57]:
##내가 구하려는 것은 W x X + b이므로 1/1+e^-(x*w +b) 시그모이드 함수 사용할 것임

In [58]:

w=torch.zeros((2,1), requires_grad=True) ## 입력값 2개, 출력값 1개 / requires_grad = True : 학습 암시
b=torch.zeros((1), requires_grad=True) ## 출력값 1개


In [59]:

hy = 1 / (1+torch.exp(-(x_train.matmul(w)+b))) 

##위의 시그모이드 함수 재현
##torch.exp는 지수 e를 의미함

'''그러나 이렇게 값 일일히 재현 힘듦
    따라서 torch.sigmoid(x_train.matmul(w)+b))로 똑같은 기능 재현 가능'''



'그러나 이렇게 값 일일히 재현 힘듦\n    따라서 torch.sigmoid(x_train.matmul(w)+b))로 똑같은 기능 재현 가능'

In [60]:

##실제 머신러닝 코드 작성

epoches=10000

optimizer = optim.SGD([w,b],lr=1) ##내가 학습할 요소 w,b를 optim.SGD로 알려줌
for e in range(epoches):
    hy = 1 / (1+torch.exp(-(x_train.matmul(w)+b)))
    cost = F.mse_loss(hy, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if e % 1000 == 0:
        print('Epoch [{}/{}], Cost: {:.6f}'.format(e, epoches, cost.item()))



Epoch [0/10000], Cost: 0.250000
Epoch [1000/10000], Cost: 0.007125
Epoch [2000/10000], Cost: 0.003398
Epoch [3000/10000], Cost: 0.002197
Epoch [4000/10000], Cost: 0.001613
Epoch [5000/10000], Cost: 0.001271
Epoch [6000/10000], Cost: 0.001046
Epoch [7000/10000], Cost: 0.000888
Epoch [8000/10000], Cost: 0.000771
Epoch [9000/10000], Cost: 0.000680


In [61]:
############################################################################

In [62]:
#테스트

hy = torch.sigmoid(x_train.matmul(w)+b)
print(hy[:-1])


tensor([[2.3470e-04],
        [3.1856e-02],
        [3.4481e-02],
        [9.6198e-01],
        [9.9858e-01]], grad_fn=<SliceBackward0>)


In [63]:
##결과 출력

prediction = hy >= torch.FloatTensor([0.5]).float()
print("예측값:\n", prediction[:5].float())
print("학습값:\n",y_train[:5])

same = prediction == y_train.bool()
print("동일한지 체크값:\n", same[:5])


예측값:
 tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.]])
학습값:
 tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.]])
동일한지 체크값:
 tensor([[True],
        [True],
        [True],
        [True],
        [True]])
