In [13]:
import numpy as np
import torch

t= torch.FloatTensor([1,2]) ##플롯 형태
print(t.mean())

tensor(1.5000)
tensor([2., 3.])


In [18]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t.mean(dim=0)) ##각각 세로축
print(t.mean(dim=1)) ##각각 가로축


tensor([2., 3.])
tensor([1.5000, 3.5000])


In [19]:
print(t.max()) ##가장 큰 값(마찬가지로 dim 사용 가능)
print(t.max(dim=0)) ##가장 큰 값(세로축)
print(t.max(dim=1)) ##가장 큰 값(가로축)


tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [29]:
t=np.array([0,1,2,3,4,5,6,7,8,9])
ft=torch.FloatTensor(t)
print(ft.view(([-1,2]))) ##-1은 끝까지를 의미; -1,2는 2개 가로축을 가지고, 나머지 자동으로 5행을 맞춰줌
print(ft.view([-1,5]))  ##5개 가로 값 가짐->2개의 열
print(ft.view([-1,2,5])) ##2개의 행, 각각의 행이 가진 값 수는 1개

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])
tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
tensor([[[0., 1., 2., 3., 4.],
         [5., 6., 7., 8., 9.]]])


In [24]:
import numpy as np
import torch

t=np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [34]:
##squuze함수는 [n,m]에서 m이 "1일 때" 크기 조정해서 m을 없애버림
ft=torch.FloatTensor([[1],[2],[3]]) ##3x1 크기
print(ft)
print(ft.squeeze()) ##1x3으로 바꿈(3)으로만 표기

tensor([[1.],
        [2.],
        [3.]])
tensor([1., 2., 3.])


In [38]:
print(ft.unsqueeze(0)) ##squueze 했던 것을 다시 복귀 (3)이면 1x3형으로 dim=0 처리
print(ft.unsqueeze(1)) ##3x1형으로 dim=1 처리

tensor([[[1.],
         [2.],
         [3.]]])
tensor([[[1.]],

        [[2.]],

        [[3.]]])


In [40]:
##값 타입 바꿔주기
## LongTensor, ByteTensor([True, False]) 등이 존재
##t.float(), t.long()처럼 형식 변환 가능

a=torch.LongTensor([1,2,3])
print(a.float())

b=torch.ByteTensor([True, False, True, False])
print(b.float())
print(b.long())

tensor([1., 2., 3.])
tensor([1., 0., 1., 0.])
tensor([1, 0, 1, 0])


In [44]:
##c언어에서 strcat처럼 cat은 두 배열 합치는데 사용함

x=torch.LongTensor([[1,2],[3,4]])
y=torch.LongTensor([[5,6],[7,8]])

print(torch.cat([x,y],dim=0)) ##각 []를 부수지 않고 쭉 이어붙임
print(torch.cat([x,y],dim=1)) ##각 []를 부수고 각 행에 맞는 값을 하나의 []로 묶어버림

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [50]:
##스택은 말 그래도 쌓는 것을 의미 위의 cat과 비슷함

x=torch.LongTensor([1,2])
y=torch.LongTensor([3,4])
z=torch.LongTensor([5,6])

print(torch.stack([x,y,z])) ##블록 쌓듯이 포개버림
print(torch.stack([x,y,z], dim=1)) ##위와 비슷(각 행에 맞는 값 하나로)

##아래 코드와 동일하다
##unsqueeze 통해 1x2 배열로 다시 돌려놓음
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)],dim=0)) ##unsqueeze 안할시 1x6 배열 되버림


tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 3, 5],
        [2, 4, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [51]:
x=torch.LongTensor([[2,3,4],[6,7,8]])
print(torch.ones_like(x))
print(torch.zeros_like(x)) ##모든 값 묵살 후 1 혹은 0으로 초기화

tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0, 0, 0],
        [0, 0, 0]])


In [52]:
x=torch.LongTensor([[1,2],[3,4]])

print(x.mul(2)) ##곱셈 계산 
print(x) 
print(x.mul_(2)) ##곱셈 계산 후 기존 값 덮어 씌우기
print(x)

tensor([[2, 4],
        [6, 8]])
tensor([[2, 4],
        [6, 8]])
tensor([[2, 4],
        [6, 8]])
