In [112]:
##5주차에서 만든 것을 강의 안보고 내가 class 정의해서 만륾

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
import torch.nn.functional as F


torch.manual_seed(1)

x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]

x = torch.FloatTensor(x_data)
y = torch.FloatTensor(y_data)

class binary(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2, 1)

    def forward(self, x):
        return torch.sigmoid(self.linear(x))

model = binary()


In [113]:

w=torch.zeros((2,1), requires_grad=True) ## 입력값 2개, 출력값 1개 / requires_grad = True : 학습 암시
b=torch.zeros((1), requires_grad=True) ## 출력값 1개


In [114]:
epoches = 10000

model = binary()
optimizer = optim.SGD(model.parameters(), lr=1)

for e in range(epoches):
    hy = model(x)
    cost = F.mse_loss(hy, y)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if e % 1000 == 0:
        prediction = hy >= torch.FloatTensor([0.5]).float()
        
        print('Epoch [{}/{}], Cost: {:.6f}'.format(e, epoches, cost.item()))


Epoch [0/10000], Cost: 0.213677
Epoch [1000/10000], Cost: 0.007271
Epoch [2000/10000], Cost: 0.003433
Epoch [3000/10000], Cost: 0.002212
Epoch [4000/10000], Cost: 0.001622
Epoch [5000/10000], Cost: 0.001276
Epoch [6000/10000], Cost: 0.001050
Epoch [7000/10000], Cost: 0.000890
Epoch [8000/10000], Cost: 0.000772
Epoch [9000/10000], Cost: 0.000682


In [108]:
##최종 테스트

prediction = hy >= torch.FloatTensor([0.5]).float()
print("예측값:\n", prediction[:6].float())
print("학습값:\n", y[:6])

same = prediction == y.bool()
print("동일한지 체크값:\n", same[:6])

예측값:
 tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])
학습값:
 tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])
동일한지 체크값:
 tensor([[True],
        [True],
        [True],
        [True],
        [True],
        [True]])
